DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS cards;
PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS groups (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR
);
CREATE TABLE IF NOT EXISTS cards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR,
    description TEXT,
    groupId INT NOT NULL,
    FOREIGN KEY (groupId) REFERENCES groups(id) ON DELETE CASCADE
);